services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=kermesse
      - MYSQL_PASSWORD=kermesse
      - MYSQL_DATABASE=kermesse_db
      - MYSQL_USER=kermesse
    ports:
      - 4306:3306
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db